export const options = [
  { value: "Annual General Meetings", text: "Annual General Meetings" },
  { value: "D&M Congresses", text: "D&M Congresses" },
  { value: "Executive Board", text: "Executive Board" },
  { value: "ECL Steering Committee", text: "ECL Steering Committee" },
  {
    value: "Europeans Organization Committee",
    text: "Europeans Organization Committee",
  },
  { value: "Competition Rules Committee", text: "Competition Rules Committee" },
  { value: "Judges Committee", text: "Judges Committee" },
  { value: "Regulations", text: "Regulations" },
  { value: "General Meetings", text: "General Meetings" },
  { value: "Events Congresses", text: "Events Congresses" },
  { value: "Competitions", text: "Competitions" },
  { value: "Judges Education", text: "Judges Education" },
  { value: "Coaches Education", text: "Coaches Education" },
  { value: "ECL Rules", text: "ECL Rules" },
  { value: "ECL Results", text: "ECL Results" },
  { value: "ECL Rankings", text: "ECL Rankings" },
  { value: "ECL Scoring System", text: "ECL Scoring System" },
  { value: "ECL Competition Report", text: "ECL Competition Report" },
  { value: "ECL Application Form", text: "ECL Application Form" },
  { value: "Judges Documents", text: "Judges Documents" },
  { value: "Judges Register", text: "Judges Register" },
  { value: "Coaches Documents", text: "Coaches Documents" },
  { value: "Coaches Register", text: "Coaches Register" },
  { value: "Registration System", text: "Registration System" },
  { value: "eScoring", text: "eScoring" },
];
